language: php
php:
  - "7.2"

cache:
  directories:
    - vendor

install:
  - composer install

script:
  - composer run-script test-all

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
